const $ = (selector) => document.querySelector(selector);
const state = { token: sessionStorage.getItem('emberline_token') || '', actor: null, projects: [], project: null, selectedMilestone: null };
const MAX_EVIDENCE_BYTES = 25 * 1024 * 1024;
const money = (value) => `$${Number(value || 0).toLocaleString()}`;
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const short = (value, length = 14) => value && value.length > length ? `${value.slice(0, 8)}…${value.slice(-4)}` : value || '—';
const initials = (name) => String(name || 'E').split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();
const statusCopy = (value) => ({ funding: 'Funding', in_review: 'In review', complete: 'Complete', disputed: 'Disputed', pending: 'Locked', submitted: 'In review', released: 'Released' })[value] || value;
const showToast = (message, error = false) => { const toast = $('#toast'); toast.textContent = message; toast.className = `toast show${error ? ' error' : ''}`; clearTimeout(showToast.timer); showToast.timer = setTimeout(() => { toast.className = 'toast'; }, 3200); };
const openModal = (id) => { const modal = $(`#${id}`); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); };
const closeModal = (id) => { const modal = $(`#${id}`); modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); };
const request = async (path, options = {}) => {
  const headers = { ...(options.body ? { 'content-type': 'application/json' } : {}), ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...(options.method && options.method !== 'GET' ? { 'idempotency-key': crypto.randomUUID() } : {}), ...options.headers };
  const response = await fetch(path, { ...options, headers }); const data = await response.json();
  if (!response.ok) throw new Error(data.message || data.error || 'Request failed'); return data;
};
const activeMilestone = () => state.project?.milestones.find((m) => ['submitted', 'disputed'].includes(m.state)) || state.project?.milestones.find((m) => m.state === 'pending');
const actorCan = (role) => state.actor?.role === role;

function renderIdentity() {
  $('#identityName').textContent = state.actor?.name || 'Read-only visitor'; $('#identityRole').textContent = state.actor?.role || 'Connect an actor';
  $('.identity-avatar').textContent = initials(state.actor?.name || 'Visitor'); $('#connectButton').textContent = state.actor ? 'Switch actor' : 'Connect actor';
  $('#newProjectButton').disabled = !actorCan('owner'); $('#fundButton').disabled = !actorCan('owner');
}
function renderProjectSwitcher() {
  $('#projectList').innerHTML = state.projects.map((p) => `<button class="project-item ${p.id === state.project?.id ? 'selected' : ''}" data-project="${escapeHtml(p.id)}"><span class="project-monogram">${escapeHtml(initials(p.name))}</span><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.category)} · ${escapeHtml(statusCopy(p.status))}</small></span></button>`).join('');
  document.querySelectorAll('[data-project]').forEach((button) => button.addEventListener('click', () => loadProject(button.dataset.project)));
}
function renderProject() {
  const p = state.project; if (!p) return;
  const active = activeMilestone(); state.selectedMilestone = active?.id;
  const percent = Math.min(100, Math.round((p.funded_amount / p.target_amount) * 100)); const implementer = p.implementer_actor_id === 'implementer-atlas' ? 'Atlas Works' : p.implementer_actor_id;
  const activeMonogram = document.querySelector('.project-item.selected .project-monogram'); if (activeMonogram) activeMonogram.textContent = initials(p.name);
  $('#projectCategory').textContent = p.category.toUpperCase(); $('#projectState').textContent = statusCopy(p.status).toUpperCase(); $('#projectName').textContent = p.name; $('#projectSummary').textContent = p.summary;
  $('#implementerName').textContent = implementer; $('.implementer-mark').textContent = initials(implementer); $('#capitalPercent').textContent = `${percent}%`; $('#capitalBar').style.width = `${percent}%`;
  $('#fundedAmount').textContent = money(p.funded_amount); $('#targetAmount').textContent = money(p.target_amount); $('#lockedAmount').textContent = money(p.funded_amount - p.released_amount); $('#releasedAmount').textContent = money(p.released_amount);
  $('#nextAmount').textContent = active ? money(active.amount) : 'Complete'; $('#nextGateCopy').textContent = active?.state === 'disputed' ? 'Frozen · submit a new revision' : active ? `${Math.max(0, active.quorum - active.approvals)} more independent approval${active.quorum - active.approvals === 1 ? '' : 's'}` : 'All milestones processed';
  $('#impactValue').textContent = `${Number(p.confirmed_impact || 0).toLocaleString()} / ${Number(p.impact_target || 0).toLocaleString()}`; $('#impactUnit').textContent = p.impact_unit;
  $('#auditStatus').textContent = p.audit?.valid ? `AUDIT CHAIN VERIFIED · ${p.audit.checked} EVENTS` : 'AUDIT CHAIN NEEDS REVIEW'; $('#auditStatus').className = `audit-status ${p.audit?.valid ? 'valid' : 'invalid'}`;
  renderProjectSwitcher(); renderMilestones(); renderReviewers(); renderActivity(); renderIdentity();
}
function renderMilestones() {
  const p = state.project;
  $('#milestoneList').innerHTML = p.milestones.map((m) => {
    const canEvidence = actorCan('implementer') && state.actor.id === p.implementer_actor_id && ['pending', 'disputed'].includes(m.state);
    const evidence = m.evidence_commitment ? `<span title="${escapeHtml(m.evidence_commitment)}">commit ${escapeHtml(short(m.evidence_commitment))}</span>` : '<span>evidence not submitted</span>';
    const history = m.evidenceHistory?.length > 1 ? `<span>${m.evidenceHistory.length} revisions</span>` : '';
    const copy = m.state === 'released' ? 'Release conditions were satisfied and the tranche was recorded.' : m.state === 'disputed' ? 'A reviewer rejected this revision. Capital is frozen until a new package is submitted.' : m.state === 'submitted' ? 'Evidence is committed and independent review is open.' : 'This gate is waiting for an evidence package.';
    return `<article class="milestone ${escapeHtml(m.state)}"><div class="milestone-dot">${m.state === 'released' ? '✓' : String(m.sequence).padStart(2, '0')}</div><div class="milestone-body"><div class="milestone-row"><strong>${escapeHtml(m.title)}</strong><span class="tag ${escapeHtml(m.state)}">${escapeHtml(statusCopy(m.state).toUpperCase())}</span></div><p>${copy}</p><div class="milestone-meta">${evidence}<span>rev ${m.revision}</span>${history}<span>${m.approvals}/${m.quorum} approvals</span><b>${money(m.amount)}</b>${canEvidence ? `<button class="evidence-action" data-evidence="${m.id}">${m.state === 'disputed' ? 'Submit new revision' : 'Submit evidence'} ↗</button>` : ''}</div></div></article>`;
  }).join('');
  document.querySelectorAll('[data-evidence]').forEach((button) => button.addEventListener('click', () => { state.selectedMilestone = Number(button.dataset.evidence); const milestone = p.milestones.find((m) => m.id === state.selectedMilestone); $('#evidenceLabel').value = milestone?.state === 'disputed' ? `Revision ${Number(milestone.revision) + 1} evidence package` : 'Evidence package'; $('#evidenceCommitment').value = ''; $('#evidenceFile').value = ''; $('#evidenceHelper').textContent = milestone?.state === 'disputed' ? 'This creates a new immutable revision. Previous reviews remain in the audit trail.' : 'Choose a private file to hash locally. The file never leaves this browser.'; openModal('evidenceModal'); }));
}
function renderReviewers() {
  const active = activeMilestone(); if (!active) { $('#reviewerList').innerHTML = '<p class="empty-state">All milestones are complete.</p>'; $('#releaseButton').disabled = true; return; }
  $('#reviewEyebrow').textContent = `MILESTONE ${String(active.sequence).padStart(2, '0')} · REVISION ${active.revision}`; $('#quorumBadge').textContent = active.state === 'disputed' ? 'DISPUTED' : `${active.approvals} / ${active.quorum}`; $('#quorumBadge').classList.toggle('disputed', active.state === 'disputed');
  const reviews = new Map(active.reviews.map((review) => [review.actor_id, review]));
  $('#reviewerList').innerHTML = state.project.reviewers.map((reviewer) => { const review = reviews.get(reviewer.id); const ownSession = state.actor?.id === reviewer.id; const canReview = ownSession && active.state === 'submitted' && !review; const status = review ? review.decision : 'pending'; return `<div class="reviewer"><span class="reviewer-avatar">${initials(reviewer.name)}</span><span class="reviewer-info"><strong>${escapeHtml(reviewer.name)}</strong><small>${escapeHtml(reviewer.role)} · ${review ? `attestation ${escapeHtml(short(review.attestation_ref))}` : 'independent review'}</small></span>${canReview ? `<span class="review-actions"><button data-review="approved">Approve</button><button class="reject" data-review="rejected">Flag</button></span>` : `<span class="review-status ${status}">${status === 'approved' ? '✓ approved' : status === 'rejected' ? '⚑ disputed' : ownSession ? 'your review' : 'pending'}</span>`}</div>`; }).join('');
  document.querySelectorAll('[data-review]').forEach((button) => button.addEventListener('click', () => { state.pendingDecision = button.dataset.review; $('#reviewDecision').textContent = button.dataset.review === 'approved' ? 'Approve evidence' : 'Flag evidence'; $('#attestationRef').value = `local:${state.actor.id}:${Date.now()}`; openModal('reviewModal'); }));
  const canRelease = actorCan('owner') && active.state === 'submitted' && active.approvals >= active.quorum && active.rejections === 0; $('#releaseButton').disabled = !canRelease; $('#releaseButton').textContent = active.state === 'disputed' ? 'Release frozen by dispute' : canRelease ? `Release ${money(active.amount)} tranche →` : 'Waiting for verified quorum';
}
function renderActivity() { const names = { project_created: 'Project created', funding_recorded: 'Capital committed', evidence_submitted: 'Evidence committed', review_approved: 'Review approved', review_rejected: 'Milestone disputed', milestone_released: 'Tranche released' }; $('#activityList').innerHTML = state.project.events.length ? state.project.events.slice(0, 8).map((event) => `<div class="activity ${event.type.includes('released') ? 'release' : event.type.includes('approved') ? 'approval' : event.type.includes('rejected') ? 'rejection' : ''}"><i></i><span><strong>${escapeHtml(names[event.type] || event.detail)}</strong><small>${escapeHtml(event.actor_name)} · ${new Date(event.created_at).toLocaleString()}</small></span><code title="${escapeHtml(event.event_hash)}">${escapeHtml(short(event.event_hash))}</code></div>`).join('') : '<div class="empty-state">No activity yet.</div>'; }

async function loadSession() { state.actor = (await request('/api/session')).actor; if (state.token && !state.actor) { state.token = ''; sessionStorage.removeItem('emberline_token'); } renderIdentity(); }
async function loadProjects(preferredId) { state.projects = (await request('/api/projects')).projects; const id = preferredId || state.project?.id || state.projects[0]?.id; renderProjectSwitcher(); if (id) await loadProject(id); }
async function loadProject(id) { state.project = await request(`/api/projects/${encodeURIComponent(id)}`); renderProject(); }
async function submitEvidence() { try { const milestoneId = state.selectedMilestone || activeMilestone()?.id; state.project = await request(`/api/milestones/${milestoneId}/evidence`, { method: 'POST', body: JSON.stringify({ label: $('#evidenceLabel').value.trim(), commitment: $('#evidenceCommitment').value.trim() }) }); closeModal('evidenceModal'); renderProject(); showToast('Immutable evidence revision persisted.'); } catch (error) { showToast(error.message, true); } }
async function submitReview() { try { const active = activeMilestone(); state.project = await request(`/api/milestones/${active.id}/review`, { method: 'POST', body: JSON.stringify({ decision: state.pendingDecision, attestationRef: $('#attestationRef').value.trim(), sourceTxHash: $('#sourceTxHash').value.trim() || undefined }) }); closeModal('reviewModal'); renderProject(); showToast(state.pendingDecision === 'approved' ? 'Independent approval recorded.' : 'Milestone disputed. Funds remain locked.'); } catch (error) { showToast(error.message, true); } }
async function releaseMilestone() { try { const active = activeMilestone(); state.project = await request(`/api/milestones/${active.id}/release`, { method: 'POST' }); renderProject(); showToast(`${money(active.amount)} released after policy verification.`); } catch (error) { showToast(error.message, true); } }
async function fundProject() { try { state.project = await request(`/api/projects/${state.project.id}/fund`, { method: 'POST', body: JSON.stringify({ amount: Number($('#fundAmount').value), sourceTxHash: $('#fundTxHash').value.trim() || undefined }) }); closeModal('fundModal'); renderProject(); showToast('Capital commitment persisted.'); } catch (error) { showToast(error.message, true); } }
async function createProject() { try { const titles = [...document.querySelectorAll('.new-m-title')]; const amounts = [...document.querySelectorAll('.new-m-amount')]; const milestones = titles.map((input, i) => ({ title: input.value.trim(), amount: Number(amounts[i].value), quorum: 2 })); const project = await request('/api/projects', { method: 'POST', body: JSON.stringify({ name: $('#newName').value.trim(), category: $('#newCategory').value.trim(), summary: $('#newSummary').value.trim(), targetAmount: Number($('#newTarget').value), impactTarget: Number($('#newImpact').value), impactUnit: $('#newImpactUnit').value.trim(), milestones }) }); closeModal('newProjectModal'); await loadProjects(project.id); showToast('Project created with persistent policy records.'); } catch (error) { showToast(error.message, true); } }
async function saveIdentity() { const token = $('#actorToken').value.trim(); state.token = token; if (token) sessionStorage.setItem('emberline_token', token); try { await loadSession(); if (!state.actor) throw new Error('Token was not recognized.'); closeModal('identityModal'); renderProject(); showToast(`Connected as ${state.actor.name}.`); } catch (error) { state.actor = null; renderIdentity(); showToast(error.message, true); } }
async function hashEvidenceFile() { const file = $('#evidenceFile').files[0]; if (!file) return; if (file.size > MAX_EVIDENCE_BYTES) { $('#evidenceFile').value = ''; showToast('Evidence files must be 25 MB or smaller for local hashing.', true); return; } try { $('#evidenceHelper').textContent = `Hashing ${file.name} locally…`; const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); const commitment = `0x${[...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')}`; $('#evidenceCommitment').value = commitment; if (!$('#evidenceLabel').value.trim() || $('#evidenceLabel').value === 'Evidence package') $('#evidenceLabel').value = file.name; $('#evidenceHelper').textContent = `${file.name} hashed locally. Only the commitment will be submitted.`; } catch { showToast('This browser could not hash the selected file.', true); } }
function disconnect() { state.token = ''; state.actor = null; sessionStorage.removeItem('emberline_token'); $('#actorToken').value = ''; closeModal('identityModal'); renderIdentity(); renderProject(); showToast('Returned to read-only mode.'); }

document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => closeModal(button.dataset.close)));
document.querySelectorAll('.modal').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.id); }));
$('#connectButton').addEventListener('click', () => openModal('identityModal')); $('#identityButton').addEventListener('click', () => openModal('identityModal')); $('#newProjectButton').addEventListener('click', () => openModal('newProjectModal')); $('#fundButton').addEventListener('click', () => openModal('fundModal'));
$('#saveIdentityButton').addEventListener('click', saveIdentity); $('#disconnectButton').addEventListener('click', disconnect); $('#submitEvidenceButton').addEventListener('click', submitEvidence); $('#submitReviewButton').addEventListener('click', submitReview); $('#createProjectButton').addEventListener('click', createProject); $('#fundProjectButton').addEventListener('click', fundProject); $('#releaseButton').addEventListener('click', releaseMilestone); $('#refreshButton').addEventListener('click', () => loadProject(state.project.id)); $('#viewEvidenceButton').addEventListener('click', () => $('#milestones').scrollIntoView({ behavior: 'smooth' }));
$('#evidenceFile').addEventListener('change', hashEvidenceFile);
document.querySelectorAll('[data-token]').forEach((button) => button.addEventListener('click', () => { $('#actorToken').value = button.dataset.token; }));

(async () => { try { const health = await request('/health'); const chain = health.attestcoin || {}; $('#chainStatus').textContent = chain.mode === 'unconfigured' ? 'Adapter · configure Attestcoin' : `${chain.network} · ${chain.mode}`; if (!health.demoCredentials) $('#demoCredentials').hidden = true; await loadSession(); await loadProjects(); } catch (error) { showToast(error.message, true); } })();
