const $ = (selector) => document.querySelector(selector);
const state = { token: sessionStorage.getItem('emberline_token') || '', demoJourneyId: sessionStorage.getItem('emberline_demo_journey') || '', actor: null, projects: [], project: null, selectedMilestone: null, guideStep: 0, guideRole: localStorage.getItem('emberline_guide_role') || 'visitor' };
const MAX_EVIDENCE_BYTES = 25 * 1024 * 1024;
const money = (value) => `$${Number(value || 0).toLocaleString()}`;
const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
const short = (value, length = 14) => value && value.length > length ? `${value.slice(0, 8)}…${value.slice(-4)}` : value || '—';
const initials = (name) => String(name || 'E').split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase();
const statusCopy = (value) => ({ funding: 'Funding', in_review: 'In review', complete: 'Complete', disputed: 'Disputed', pending: 'Locked', submitted: 'In review', released: 'Released' })[value] || value;
const showToast = (message, error = false) => { const toast = $('#toast'); toast.textContent = message; toast.className = `toast show${error ? ' error' : ''}`; clearTimeout(showToast.timer); showToast.timer = setTimeout(() => { toast.className = 'toast'; }, 3200); };
const openModal = (id) => { const modal = $(`#${id}`); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); };
const closeModal = (id) => { const modal = $(`#${id}`); modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); };
const request = async (path, options = {}) => {
  const headers = { ...(options.body ? { 'content-type': 'application/json' } : {}), ...(state.token ? { authorization: `Bearer ${state.token}` } : {}), ...(options.method && options.method !== 'GET' ? { 'idempotency-key': crypto.randomUUID() } : {}), ...options.headers };
  const response = await fetch(path, { ...options, headers }); const data = await response.json();
  if (!response.ok) throw new Error(data.message || data.error || 'Request failed'); return data;
};
const activeMilestone = () => state.project?.milestones.find((m) => m.state !== 'released');
const actorCan = (role) => state.actor?.role === role;
const demoStage = () => {
  if (!state.actor?.demo || !state.project) return null;
  const milestone = state.project.milestones.find((item) => item.sequence === 2);
  if (!milestone || milestone.state === 'released') return { index: 4, roleId: null, code: null, title: 'Application verification complete', copy: 'This session created one local evidence commitment, two independent application attestations, and one policy-controlled release record.', button: 'Inspect the recorded audit trail →' };
  if (milestone.state === 'pending' || milestone.state === 'disputed') return { index: 0, roleId: 'demo-implementer', code: 'EMBER-BUILDER', title: 'Generate a session-specific evidence commitment', copy: 'Create a unique Network installation record for this sandbox, hash it locally, and persist only its commitment.', button: 'Generate evidence →' };
  const reviewed = new Set(milestone.reviews.map((review) => review.actor_id));
  if (!reviewed.has('demo-reviewer-one')) return { index: 1, roleId: 'demo-reviewer-one', code: 'EMBER-REVIEW-1', title: 'Record the technical review', copy: 'Switch to the first independent role and create a fresh application attestation for this exact revision.', button: 'Continue as Reviewer 1 →' };
  if (!reviewed.has('demo-reviewer-two')) return { index: 2, roleId: 'demo-reviewer-two', code: 'EMBER-REVIEW-2', title: 'Complete the application quorum', copy: 'Create the second independent attestation required by this sandbox policy.', button: 'Continue as Reviewer 2 →' };
  return { index: 3, roleId: 'demo-owner', code: 'EMBER-OWNER', title: 'Record the policy-controlled release', copy: 'Application quorum is satisfied. Continue as the Capital Owner to record the scenario’s $6,000 release.', button: 'Continue as Capital Owner →' };
};
const guideSteps = ['Your role', 'Capital states', 'Your route', 'Verification', 'Ready'];
const guideRoles = {
  visitor: { label: 'Explore', icon: '◎', copy: 'Understand project status, committed capital, evidence, and the audit trail.', title: 'Read the full accountability story.', route: ['Start with capital progress and locked funds', 'Inspect each milestone and evidence revision', 'Use the audit trail to verify who did what'], target: '#overview', action: 'Explore this workspace' },
  owner: { label: 'Capital owner', icon: '◇', copy: 'Create projects, commit capital, monitor quorum, and release eligible tranches.', title: 'Fund work without surrendering control.', route: ['Create a milestone-funded project', 'Commit capital to its accountability workspace', 'Release only after independent quorum'], target: '.project-hero', action: 'View capital controls' },
  implementer: { label: 'Implementer', icon: '↗', copy: 'Submit private work packages as immutable SHA-256 evidence commitments.', title: 'Turn completed work into verifiable progress.', route: ['Open the active milestone gate', 'Hash evidence privately in your browser', 'Submit a new immutable revision when needed'], target: '#milestones', action: 'Go to milestone ledger' },
  reviewer: { label: 'Reviewer', icon: '✓', copy: 'Independently approve or flag the active evidence revision.', title: 'Make review accountable and independent.', route: ['Inspect the exact evidence revision', 'Approve or flag with an attestation reference', 'Let quorum—or a dispute—control release'], target: '#reviewers', action: 'Go to review network' }
};
const coachTours = {
  visitor: [
    { target: '#projectList', eyebrow: 'CHOOSE A WORKSPACE', title: 'Click a project to switch context.', copy: 'Every dashboard view, milestone, reviewer, and audit event updates to the selected project.' },
    { target: '.capital-card', eyebrow: 'READ CAPITAL STATE', title: 'Start with committed versus target.', copy: 'This card shows funding progress and whether the project audit hash chain is currently valid.' },
    { target: '#milestones', eyebrow: 'INSPECT THE WORK', title: 'Click through the milestone ledger.', copy: 'Each gate shows its amount, evidence commitment, revision number, approvals, and current release state.' },
    { target: '#reviewers', eyebrow: 'CHECK INDEPENDENCE', title: 'See who must approve.', copy: 'This panel shows quorum progress and makes disputes visible before any capital can move.' },
    { target: '#activity', eyebrow: 'VERIFY HISTORY', title: 'Finish at the audit trail.', copy: 'Refresh here to inspect the latest hash-chained project actions and their references.' }
  ],
  owner: [
    { target: '#connectButton', eyebrow: 'FIRST: CONNECT', title: 'Connect your owner actor token.', copy: 'Click here and paste the server-issued owner token. The guide itself never grants owner permissions.' },
    { target: '#newProjectButton', eyebrow: 'CREATE', title: 'Press “New project” to define policy.', copy: 'Set the target, impact goal, milestone amounts, and required approval quorum.' },
    { target: '#fundButton', eyebrow: 'COMMIT CAPITAL', title: 'Record project funding here.', copy: 'This control is enabled only for a connected owner and records the source transaction when available.' },
    { target: '#reviewers', eyebrow: 'WATCH THE GATE', title: 'Wait for verified quorum.', copy: 'Approvals apply to one exact evidence revision. A single rejection freezes the active tranche.' },
    { target: '#releaseButton', eyebrow: 'RELEASE', title: 'Press release only when enabled.', copy: 'The API rechecks role, sequence, funding, quorum, and dispute conditions before recording release.' }
  ],
  implementer: [
    { target: '#connectButton', eyebrow: 'FIRST: CONNECT', title: 'Connect your implementer actor token.', copy: 'The token is checked server-side and must match the implementer assigned to this project.' },
    { target: '#milestones', eyebrow: 'FIND THE ACTIVE GATE', title: 'Open the milestone ledger.', copy: 'The first pending or disputed milestone is where your next immutable work package belongs.' },
    { target: '#viewEvidenceButton', eyebrow: 'JUMP TO EVIDENCE', title: 'Press “Inspect evidence trail.”', copy: 'This shortcut takes you directly to commitments, revision history, and submission controls.' },
    { target: '#milestoneList', eyebrow: 'SUBMIT EVIDENCE', title: 'Press “Submit evidence” on your gate.', copy: 'After connecting the assigned implementer, this action appears on eligible milestones. The private file is hashed locally.' },
    { target: '#activity', eyebrow: 'CONFIRM THE RECORD', title: 'Check that the revision was recorded.', copy: 'The audit trail preserves the commitment and every replacement revision without uploading the private file.' }
  ],
  reviewer: [
    { target: '#connectButton', eyebrow: 'FIRST: CONNECT', title: 'Connect your reviewer actor token.', copy: 'Only an assigned independent reviewer can act on the active evidence revision.' },
    { target: '#milestones', eyebrow: 'INSPECT EVIDENCE', title: 'Read the commitment and revision.', copy: 'Confirm you are reviewing the correct work package before making a decision.' },
    { target: '#reviewers', eyebrow: 'MAKE A DECISION', title: 'Press Approve or Flag beside your name.', copy: 'The action appears only for your connected reviewer session and only once per evidence revision.' },
    { target: '.policy-note', eyebrow: 'UNDERSTAND THE POLICY', title: 'One rejection freezes release.', copy: 'A replacement evidence revision starts a fresh review cycle while preserving the disputed history.' },
    { target: '#activity', eyebrow: 'VERIFY ATTESTATION', title: 'Confirm your decision in the audit trail.', copy: 'The event binds the actor, milestone, revision, decision, and proof or attestation reference.' }
  ]
};
let coachStep = 0; let coachTarget = null;

function guideMarkup() {
  const role = state.actor?.demo && state.guideRole === 'owner' ? { ...guideRoles.owner, title: 'Release work only after independent quorum.', route: ['Review the prepared project and locked tranche', 'Confirm both independent approvals', 'Release the eligible milestone and inspect its audit event'] } : guideRoles[state.guideRole];
  if (state.guideStep === 0) return `<div class="onboarding-copy"><h2>See how verified work moves capital.</h2><p>Emberline gives owners, implementers, and independent reviewers one shared record. Choose how you want to explore—this only personalizes the guide and never grants permissions.</p><div class="role-grid">${Object.entries(guideRoles).map(([key, item]) => `<button class="role-card ${key === state.guideRole ? 'selected' : ''}" data-guide-role="${key}"><span>${item.label}<i>${item.icon}</i></span><small>${item.copy}</small></button>`).join('')}</div><div class="onboarding-note"><b>SECURE BY DESIGN</b><span>Your real role always comes from a server-issued actor token. Guide selection cannot authorize an action.</span></div></div>`;
  if (state.guideStep === 1) return '<div class="onboarding-copy"><h2>Read capital state at a glance.</h2><p>Every amount is tied to a milestone state, so “funded” never means “freely spendable.”</p><div class="state-explainer"><article><i></i><strong>Committed</strong><small>Capital recorded against the project.</small></article><article><i></i><strong>Locked</strong><small>Waiting for evidence or policy conditions.</small></article><article><i></i><strong>In review</strong><small>An exact evidence revision awaits quorum.</small></article><article><i></i><strong>Released</strong><small>All conditions passed and release was recorded.</small></article></div><div class="onboarding-note"><b>ONE REJECTION</b><span>A disputed revision freezes its tranche until the implementer submits a new immutable evidence package.</span></div></div>';
  if (state.guideStep === 2) return `<div class="onboarding-copy"><h2>${role.title}</h2><p>This is the shortest route through Emberline for a ${role.label.toLowerCase()}.</p><div class="role-route"><div class="role-route-mark">${role.icon}</div><ol>${role.route.map((item, index) => `<li><b>0${index + 1}</b><span>${item}</span></li>`).join('')}</ol></div><div class="onboarding-note"><b>ROLE-AWARE UI</b><span>Action controls appear only when the connected actor is authorized for that project and gate.</span></div></div>`;
  if (state.guideStep === 3) return '<div class="onboarding-copy"><h2>Evidence informs people. Policy controls capital.</h2><p>The release sequence is explicit, inspectable, and preserved in a tamper-evident event chain.</p><div class="audit-flow"><div><b>01</b><strong>Commit evidence</strong><small>The browser hashes the private file locally.</small></div><div><b>02</b><strong>Review revision</strong><small>Independent actors attest to one exact revision.</small></div><div><b>03</b><strong>Reach quorum</strong><small>Approvals satisfy policy; rejection freezes it.</small></div><div><b>04</b><strong>Release tranche</strong><small>The owner records release after verification.</small></div></div><div class="onboarding-note"><b>AUDITABLE</b><span>Every material action links to the previous event hash, making silent history changes detectable.</span></div></div>';
  return `<div class="onboarding-copy"><h2>You are ready to follow the line.</h2><p>Start in read-only mode, or connect a server-issued actor token when you need to perform an authorized action. The guide stays available from the top bar.</p><div class="role-route"><div class="role-route-mark">${role.icon}</div><ol><li><b>01</b><span>Selected route: <strong>${role.label}</strong></span></li><li><b>02</b><span>Open the relevant workspace section</span></li><li><b>03</b><span>Connect an actor only when an action is required</span></li></ol></div><div class="onboarding-note"><b>NO CREDENTIALS EXPOSED</b><span>Production actor tokens are never embedded in this guide or returned by the API.</span></div></div>`;
}

function renderGuide() {
  $('#onboardingEyebrow').textContent = ['WELCOME TO EMBERLINE', 'CAPITAL STATES', `${guideRoles[state.guideRole].label.toUpperCase()} ROUTE`, 'IMMUTABLE AUDIT TRAIL', 'WORKSPACE READY'][state.guideStep];
  $('#onboardingContent').innerHTML = guideMarkup();
  $('#onboardingCounter').textContent = `${state.guideStep + 1} / ${guideSteps.length}`;
  $('#onboardingBack').disabled = state.guideStep === 0; $('#onboardingNext').textContent = state.guideStep === guideSteps.length - 1 ? 'Show me where to click →' : 'Next →';
  $('#guideProgress').innerHTML = guideSteps.map((label, index) => `<div class="guide-step ${index === state.guideStep ? 'active' : index < state.guideStep ? 'complete' : ''}"><i>${index < state.guideStep ? '✓' : `0${index + 1}`}</i><span>${label}</span></div>`).join('');
  document.querySelectorAll('[data-guide-role]').forEach((button) => button.addEventListener('click', () => { state.guideRole = button.dataset.guideRole; localStorage.setItem('emberline_guide_role', state.guideRole); renderGuide(); }));
}
function openGuide(step = 0) { state.guideStep = step; renderGuide(); $('#onboarding').classList.add('open'); $('#onboarding').setAttribute('aria-hidden', 'false'); document.body.classList.add('guide-open'); $('#onboardingClose').focus(); }
function closeGuide(complete = true) { $('#onboarding').classList.remove('open'); $('#onboarding').setAttribute('aria-hidden', 'true'); document.body.classList.remove('guide-open'); if (complete) localStorage.setItem('emberline_onboarding_complete', 'true'); $('#guideButton').focus(); }
function finishGuide() { closeGuide(); if (state.actor?.demo) { $('#demoFlow').scrollIntoView({ behavior: 'smooth', block: 'center' }); return showToast('Continue from the highlighted guided demo step.'); } startCoachTour(); }
function moveGuide(direction) { const next = state.guideStep + direction; if (next < 0) return; if (next >= guideSteps.length) return finishGuide(); state.guideStep = next; renderGuide(); }
function positionCoachmark() {
  if (!coachTarget) return; const rect = coachTarget.getBoundingClientRect(); const pad = 7;
  Object.assign($('#coachmarkRing').style, { left: `${Math.max(5, rect.left - pad)}px`, top: `${Math.max(5, rect.top - pad)}px`, width: `${Math.min(innerWidth - 10, rect.width + pad * 2)}px`, height: `${Math.min(innerHeight - 10, rect.height + pad * 2)}px` });
  const tip = $('#coachmarkTip'); const tipWidth = Math.min(350, innerWidth - 28); const estimatedHeight = 205; let left = Math.min(innerWidth - tipWidth - 14, Math.max(14, rect.left)); let top = rect.bottom + 17;
  if (top + estimatedHeight > innerHeight) top = Math.max(14, rect.top - estimatedHeight - 17); if (innerWidth <= 430) { left = 10; top = rect.bottom + 14; if (top + estimatedHeight > innerHeight) top = 10; }
  Object.assign(tip.style, { left: `${left}px`, top: `${top}px` });
}
async function renderCoachStep() {
  const steps = coachTours[state.guideRole]; const step = steps[coachStep]; coachTarget?.classList.remove('coachmark-target', 'coachmark-pulse'); coachTarget = $(step.target); if (!coachTarget) return endCoachTour();
  coachTarget.scrollIntoView({ behavior: 'smooth', block: 'center' }); await new Promise((resolve) => setTimeout(resolve, 380)); coachTarget.classList.add('coachmark-target', 'coachmark-pulse');
  $('#coachmarkEyebrow').textContent = step.eyebrow; $('#coachmarkTitle').textContent = step.title; $('#coachmarkCopy').textContent = step.copy; $('#coachmarkCounter').textContent = `${coachStep + 1} / ${steps.length}`; $('#coachmarkBack').disabled = coachStep === 0; $('#coachmarkNext').textContent = coachStep === steps.length - 1 ? 'Finish ✓' : 'Next →'; positionCoachmark(); $('#coachmarkNext').focus();
}
function startCoachTour() { coachStep = 0; $('#coachmark').classList.add('open'); $('#coachmark').setAttribute('aria-hidden', 'false'); document.body.classList.add('coachmark-open'); renderCoachStep(); }
function endCoachTour() { coachTarget?.classList.remove('coachmark-target', 'coachmark-pulse'); coachTarget = null; $('#coachmark').classList.remove('open'); $('#coachmark').setAttribute('aria-hidden', 'true'); document.body.classList.remove('coachmark-open'); localStorage.setItem('emberline_context_tour_complete', 'true'); $('#guideButton').focus(); showToast('Tour complete. Reopen it anytime from Workspace guide.'); }
function moveCoach(direction) { const steps = coachTours[state.guideRole]; const next = coachStep + direction; if (next < 0) return; if (next >= steps.length) return endCoachTour(); coachStep = next; renderCoachStep(); }

function renderIdentity() {
  $('#identityName').textContent = state.actor?.name || 'Read-only visitor'; $('#identityRole').textContent = state.actor?.role || 'Connect an actor';
  if (state.actor?.demo) $('#identityRole').textContent = `${state.actor.role} · demo sandbox`;
  $('.identity-avatar').textContent = initials(state.actor?.name || 'Visitor'); $('#connectButton').textContent = state.actor ? 'Switch actor' : 'Try demo / Connect';
  $('#newProjectButton').disabled = !actorCan('owner') || Boolean(state.actor?.demo); $('#fundButton').disabled = !actorCan('owner') || Boolean(state.actor?.demo);
}
function renderDemoFlow() {
  const flow = $('#demoFlow'); const stage = demoStage(); flow.hidden = !stage; if (!stage) return;
  flow.classList.toggle('complete', stage.index === 4);
  $('#demoStepLabel').textContent = stage.index === 4 ? 'LIVE APPLICATION SANDBOX · COMPLETE' : `LIVE APPLICATION SANDBOX · STEP ${stage.index + 1} OF 4`;
  $('#demoStepTitle').textContent = stage.title; $('#demoStepCopy').textContent = stage.copy;
  $('#demoSessionRef').textContent = `SESSION ${short(state.project.id, 18)}`;
  $('#demoFlowProgress').innerHTML = [0, 1, 2, 3].map((index) => `<i class="${index < stage.index ? 'done' : index === stage.index ? 'active' : ''}"></i>`).join('');
  const ownTurn = stage.roleId && state.actor?.id === stage.roleId;
  $('#demoNextButton').textContent = stage.index === 4 ? stage.button : ownTurn ? ({ 0: 'Generate evidence →', 1: 'Record technical approval →', 2: 'Record stakeholder approval →', 3: 'Record $6,000 release →' })[stage.index] : stage.button;
}
function renderProjectSwitcher() {
  $('#projectList').innerHTML = state.projects.map((p) => `<button class="project-item ${p.id === state.project?.id ? 'selected' : ''}" data-project="${escapeHtml(p.id)}"><span class="project-monogram">${escapeHtml(initials(p.name))}</span><span><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(p.category)} · ${escapeHtml(statusCopy(p.status))}</small></span></button>`).join('');
  document.querySelectorAll('[data-project]').forEach((button) => button.addEventListener('click', () => loadProject(button.dataset.project)));
}
function renderProject() {
  const p = state.project; if (!p) return;
  const active = activeMilestone(); state.selectedMilestone = active?.id;
  const percent = Math.min(100, Math.round((p.funded_amount / p.target_amount) * 100)); const implementer = p.implementer_actor_id === 'implementer-atlas' ? 'Atlas Works' : p.implementer_actor_id;
  const activeMonogram = document.querySelector('.project-item.selected .project-monogram'); if (activeMonogram) activeMonogram.textContent = initials(p.name);
  $('#projectCategory').textContent = p.category.toUpperCase(); $('#projectState').textContent = statusCopy(p.status).toUpperCase(); $('#projectName').textContent = p.name; $('#projectSummary').textContent = p.summary;
  $('#implementerName').textContent = implementer; $('.implementer-mark').textContent = initials(implementer); $('#capitalPercent').textContent = `${percent}%`; $('#capitalBar').style.width = `${percent}%`;
  $('#fundedAmount').textContent = money(p.funded_amount); $('#targetAmount').textContent = money(p.target_amount); $('#lockedAmount').textContent = money(p.funded_amount - p.released_amount); $('#releasedAmount').textContent = money(p.released_amount);
  $('#nextAmount').textContent = active ? money(active.amount) : 'Complete'; $('#nextGateCopy').textContent = active?.state === 'disputed' ? 'Frozen · submit a new revision' : active ? `${Math.max(0, active.quorum - active.approvals)} more independent approval${active.quorum - active.approvals === 1 ? '' : 's'}` : 'All milestones processed';
  $('#impactValue').textContent = `${Number(p.confirmed_impact || 0).toLocaleString()} / ${Number(p.impact_target || 0).toLocaleString()}`; $('#impactUnit').textContent = p.impact_unit;
  $('#auditStatus').textContent = p.audit?.valid ? `APP AUDIT VERIFIED · ${p.audit.checked} EVENTS` : 'APP AUDIT NEEDS REVIEW'; $('#auditStatus').className = `audit-status ${p.audit?.valid ? 'valid' : 'invalid'}`;
  renderProjectSwitcher(); renderMilestones(); renderReviewers(); renderActivity(); renderIdentity(); renderDemoFlow();
}
function renderMilestones() {
  const p = state.project;
  const active = activeMilestone();
  $('#milestoneList').innerHTML = p.milestones.map((m) => {
    const canEvidence = actorCan('implementer') && state.actor.id === p.implementer_actor_id && m.id === active?.id && ['pending', 'disputed'].includes(m.state);
    const evidence = m.evidence_commitment ? `<span class="record-source local-hash">LOCAL HASH</span><span title="${escapeHtml(m.evidence_commitment)}">commit ${escapeHtml(short(m.evidence_commitment))}</span>` : '<span>evidence not submitted</span>';
    const history = m.evidenceHistory?.length > 1 ? `<span>${m.evidenceHistory.length} revisions</span>` : '';
    const copy = m.state === 'released' ? 'Release conditions were satisfied and the tranche was recorded.' : m.state === 'disputed' ? 'A reviewer rejected this revision. Capital is frozen until a new package is submitted.' : m.state === 'submitted' ? 'Evidence is committed and independent review is open.' : 'This gate is waiting for an evidence package.';
    return `<article class="milestone ${escapeHtml(m.state)}"><div class="milestone-dot">${m.state === 'released' ? '✓' : String(m.sequence).padStart(2, '0')}</div><div class="milestone-body"><div class="milestone-row"><strong>${escapeHtml(m.title)}</strong><span class="tag ${escapeHtml(m.state)}">${escapeHtml(statusCopy(m.state).toUpperCase())}</span></div><p>${copy}</p><div class="milestone-meta">${evidence}<span>rev ${m.revision}</span>${history}<span>${m.approvals}/${m.quorum} approvals</span><b>${money(m.amount)}</b>${canEvidence ? `<button class="evidence-action" data-evidence="${m.id}">${m.state === 'disputed' ? 'Submit new revision' : 'Submit evidence'} ↗</button>` : ''}</div></div></article>`;
  }).join('');
  document.querySelectorAll('[data-evidence]').forEach((button) => button.addEventListener('click', () => openEvidence(Number(button.dataset.evidence))));
}
function renderReviewers() {
  const active = activeMilestone(); if (!active) { $('#reviewerList').innerHTML = '<p class="empty-state">All milestones are complete.</p>'; $('#releaseButton').disabled = true; return; }
  $('#reviewEyebrow').textContent = `MILESTONE ${String(active.sequence).padStart(2, '0')} · REVISION ${active.revision}`; $('#quorumBadge').textContent = active.state === 'disputed' ? 'DISPUTED' : `${active.approvals} / ${active.quorum}`; $('#quorumBadge').classList.toggle('disputed', active.state === 'disputed');
  const reviews = new Map(active.reviews.map((review) => [review.actor_id, review]));
  $('#reviewerList').innerHTML = state.project.reviewers.map((reviewer) => { const review = reviews.get(reviewer.id); const ownSession = state.actor?.id === reviewer.id; const canReview = ownSession && active.state === 'submitted' && !review; const status = review ? review.decision : 'pending'; const proofType = review ? (/^usc:/i.test(review.attestation_ref) ? 'USC TESTNET PROOF' : 'APP ATTESTATION') : ''; return `<div class="reviewer"><span class="reviewer-avatar">${initials(reviewer.name)}</span><span class="reviewer-info"><strong>${escapeHtml(reviewer.name)}</strong><small>${escapeHtml(reviewer.role)} · ${review ? `${proofType} ${escapeHtml(short(review.attestation_ref))}` : 'independent review'}</small></span>${canReview ? `<span class="review-actions"><button data-review="approved">Approve</button><button class="reject" data-review="rejected">Flag</button></span>` : `<span class="review-status ${status}">${status === 'approved' ? '✓ approved' : status === 'rejected' ? '⚑ disputed' : ownSession ? 'your review' : 'pending'}</span>`}</div>`; }).join('');
  document.querySelectorAll('[data-review]').forEach((button) => button.addEventListener('click', () => { state.pendingDecision = button.dataset.review; $('#reviewDecision').textContent = button.dataset.review === 'approved' ? 'Approve evidence' : 'Flag evidence'; $('#attestationRef').value = `local:${state.actor.id}:${Date.now()}`; openModal('reviewModal'); }));
  const canRelease = actorCan('owner') && active.state === 'submitted' && active.approvals >= active.quorum && active.rejections === 0; $('#releaseButton').disabled = !canRelease; $('#releaseButton').textContent = active.state === 'disputed' ? 'Release frozen by dispute' : canRelease ? `Release ${money(active.amount)} tranche →` : 'Waiting for verified quorum';
}
function renderActivity() { const names = { project_created: 'Project created', funding_recorded: 'Capital recorded', evidence_submitted: 'Evidence commitment persisted', review_approved: 'Review attestation recorded', review_rejected: 'Milestone disputed', milestone_released: 'Policy release recorded' }; $('#activityList').innerHTML = state.project.events.length ? state.project.events.slice(0, 8).map((event) => { const source = event.type === 'evidence_submitted' ? ['LOCAL HASH', 'local-hash'] : /^usc:/i.test(event.reference || '') ? ['USC TESTNET PROOF', 'testnet-record'] : (/^0x[0-9a-f]{64}$/i.test(event.reference || '') && event.type !== 'evidence_submitted') ? ['TESTNET TX', 'testnet-record'] : ['LIVE APP RECORD', 'app-record']; return `<div class="activity ${event.type.includes('released') ? 'release' : event.type.includes('approved') ? 'approval' : event.type.includes('rejected') ? 'rejection' : ''}"><i></i><span><strong>${escapeHtml(names[event.type] || event.detail)}</strong><small>${escapeHtml(event.actor_name)} · ${new Date(event.created_at).toLocaleString()}</small><em class="record-source ${source[1]}">${source[0]}</em></span><code title="${escapeHtml(event.event_hash)}">${escapeHtml(short(event.event_hash))}</code></div>`; }).join('') : '<div class="empty-state">No activity yet.</div>'; }

async function loadSession() { state.actor = (await request('/api/session')).actor; if (state.actor?.demo) { state.demoJourneyId = state.actor.journeyId || state.demoJourneyId; if (state.demoJourneyId) sessionStorage.setItem('emberline_demo_journey', state.demoJourneyId); } if (state.token && !state.actor) { state.token = ''; state.demoJourneyId = ''; sessionStorage.removeItem('emberline_token'); sessionStorage.removeItem('emberline_demo_journey'); } renderIdentity(); }
async function loadProjects(preferredId) { state.projects = (await request('/api/projects')).projects; const id = preferredId || state.project?.id || state.projects[0]?.id; renderProjectSwitcher(); if (id) await loadProject(id); }
async function loadProject(id) { state.project = await request(`/api/projects/${encodeURIComponent(id)}`); renderProject(); }
function openEvidence(milestoneId) { state.selectedMilestone = milestoneId; const milestone = state.project.milestones.find((item) => item.id === milestoneId); $('#evidenceLabel').value = milestone?.state === 'disputed' ? `Revision ${Number(milestone.revision) + 1} evidence package` : 'Evidence package'; $('#evidenceCommitment').value = ''; $('#evidenceFile').value = ''; $('#sampleEvidenceButton').hidden = !state.actor?.demo; $('#evidenceAdvanced').open = !state.actor?.demo; $('#evidenceHelper').textContent = milestone?.state === 'disputed' ? 'This creates a new immutable revision. Previous reviews remain in the audit trail.' : state.actor?.demo ? 'Generate a session-specific record below. The browser hashes it locally before Emberline persists the commitment.' : 'Choose a private file to hash locally. The file never leaves this browser.'; openModal('evidenceModal'); }
async function useSampleEvidence() { const source = `emberline:${state.project?.id}:network-installation:${Date.now()}`; const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(source)); $('#evidenceCommitment').value = `0x${[...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')}`; $('#evidenceLabel').value = `Network installation record · ${new Date().toLocaleString()}`; $('#evidenceHelper').textContent = 'Session-specific input generated and hashed locally. Persisting it will create a live application record—not a blockchain transaction.'; $('#submitEvidenceButton').focus(); }
async function submitEvidence() { try { const milestoneId = state.selectedMilestone || activeMilestone()?.id; state.project = await request(`/api/milestones/${milestoneId}/evidence`, { method: 'POST', body: JSON.stringify({ label: $('#evidenceLabel').value.trim(), commitment: $('#evidenceCommitment').value.trim() }) }); closeModal('evidenceModal'); renderProject(); showToast('Evidence commitment stored as a live application record.'); } catch (error) { showToast(error.message, true); } }
async function submitReview() { try { const active = activeMilestone(); state.project = await request(`/api/milestones/${active.id}/review`, { method: 'POST', body: JSON.stringify({ decision: state.pendingDecision, attestationRef: $('#attestationRef').value.trim(), sourceTxHash: $('#sourceTxHash').value.trim() || undefined }) }); closeModal('reviewModal'); renderProject(); showToast(state.pendingDecision === 'approved' ? 'Independent approval recorded.' : 'Milestone disputed. Funds remain locked.'); } catch (error) { showToast(error.message, true); } }
async function submitDemoApproval() { try { const active = activeMilestone(); state.project = await request(`/api/milestones/${active.id}/review`, { method: 'POST', body: JSON.stringify({ decision: 'approved', attestationRef: `local:${state.actor.id}:${Date.now()}` }) }); renderProject(); showToast(`${state.actor.name} application attestation recorded.`); } catch (error) { showToast(error.message, true); } }
async function releaseMilestone() { try { const active = activeMilestone(); state.project = await request(`/api/milestones/${active.id}/release`, { method: 'POST' }); renderProject(); showToast(state.actor?.demo ? `${money(active.amount)} policy release stored as a live application record.` : `${money(active.amount)} released after policy verification.`); } catch (error) { showToast(error.message, true); } }
async function fundProject() { try { state.project = await request(`/api/projects/${state.project.id}/fund`, { method: 'POST', body: JSON.stringify({ amount: Number($('#fundAmount').value), sourceTxHash: $('#fundTxHash').value.trim() || undefined }) }); closeModal('fundModal'); renderProject(); showToast('Capital commitment persisted.'); } catch (error) { showToast(error.message, true); } }
async function createProject() { try { const titles = [...document.querySelectorAll('.new-m-title')]; const amounts = [...document.querySelectorAll('.new-m-amount')]; const milestones = titles.map((input, i) => ({ title: input.value.trim(), amount: Number(amounts[i].value), quorum: 2 })); const project = await request('/api/projects', { method: 'POST', body: JSON.stringify({ name: $('#newName').value.trim(), category: $('#newCategory').value.trim(), summary: $('#newSummary').value.trim(), targetAmount: Number($('#newTarget').value), impactTarget: Number($('#newImpact').value), impactUnit: $('#newImpactUnit').value.trim(), milestones }) }); closeModal('newProjectModal'); await loadProjects(project.id); showToast('Project created with persistent policy records.'); } catch (error) { showToast(error.message, true); } }
async function saveIdentity() { const token = $('#actorToken').value.trim(); state.token = token; if (token) sessionStorage.setItem('emberline_token', token); try { await loadSession(); if (!state.actor) throw new Error('Token was not recognized.'); closeModal('identityModal'); renderProject(); showToast(`Connected as ${state.actor.name}.`); } catch (error) { state.actor = null; renderIdentity(); showToast(error.message, true); } }
async function startDemo(code = $('#demoCode').value) { try { const session = await request('/api/demo/session', { method: 'POST', body: JSON.stringify({ code: String(code || '').trim(), journeyId: state.demoJourneyId || undefined }) }); state.token = session.token; state.actor = session.actor; state.demoJourneyId = session.journeyId; sessionStorage.setItem('emberline_token', session.token); sessionStorage.setItem('emberline_demo_journey', session.journeyId); state.guideRole = session.actor.role === 'implementer' ? 'implementer' : session.actor.role === 'reviewer' ? 'reviewer' : 'owner'; localStorage.setItem('emberline_guide_role', state.guideRole); closeModal('identityModal'); if ($('#coachmark').classList.contains('open')) endCoachTour(); await loadProjects(session.actor.projectId); showToast(`${session.actor.name} ready. Follow the highlighted next step.`); } catch (error) { showToast(error.message, true); } }
async function hashEvidenceFile() { const file = $('#evidenceFile').files[0]; if (!file) return; if (file.size > MAX_EVIDENCE_BYTES) { $('#evidenceFile').value = ''; showToast('Evidence files must be 25 MB or smaller for local hashing.', true); return; } try { $('#evidenceHelper').textContent = `Hashing ${file.name} locally…`; const digest = await crypto.subtle.digest('SHA-256', await file.arrayBuffer()); const commitment = `0x${[...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, '0')).join('')}`; $('#evidenceCommitment').value = commitment; if (!$('#evidenceLabel').value.trim() || $('#evidenceLabel').value === 'Evidence package') $('#evidenceLabel').value = file.name; $('#evidenceHelper').textContent = `${file.name} hashed locally. Only the commitment will be submitted.`; } catch { showToast('This browser could not hash the selected file.', true); } }
async function disconnect() { state.token = ''; state.actor = null; state.demoJourneyId = ''; sessionStorage.removeItem('emberline_token'); sessionStorage.removeItem('emberline_demo_journey'); $('#actorToken').value = ''; closeModal('identityModal'); $('#demoFlow').hidden = true; renderIdentity(); await loadProjects(); showToast('Returned to read-only mode.'); }

async function advanceDemo() {
  const stage = demoStage(); if (!stage) return;
  if (stage.index === 4) return $('#activity').scrollIntoView({ behavior: 'smooth' });
  if (state.actor?.id !== stage.roleId) return startDemo(stage.code);
  if (stage.index === 0) { openEvidence(activeMilestone().id); return useSampleEvidence(); }
  if (stage.index === 1 || stage.index === 2) return submitDemoApproval();
  if (stage.index === 3) return releaseMilestone();
}

document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => closeModal(button.dataset.close)));
document.querySelectorAll('.modal').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.id); }));
$('#connectButton').addEventListener('click', () => openModal('identityModal')); $('#identityButton').addEventListener('click', () => openModal('identityModal')); $('#newProjectButton').addEventListener('click', () => openModal('newProjectModal')); $('#fundButton').addEventListener('click', () => openModal('fundModal'));
$('#saveIdentityButton').addEventListener('click', saveIdentity); $('#disconnectButton').addEventListener('click', disconnect); $('#submitEvidenceButton').addEventListener('click', submitEvidence); $('#submitReviewButton').addEventListener('click', submitReview); $('#createProjectButton').addEventListener('click', createProject); $('#fundProjectButton').addEventListener('click', fundProject); $('#releaseButton').addEventListener('click', releaseMilestone); $('#refreshButton').addEventListener('click', () => loadProject(state.project.id)); $('#viewEvidenceButton').addEventListener('click', () => $('#milestones').scrollIntoView({ behavior: 'smooth' }));
$('#evidenceFile').addEventListener('change', hashEvidenceFile);
$('#sampleEvidenceButton').addEventListener('click', useSampleEvidence); $('#guidedDemoButton').addEventListener('click', () => { state.demoJourneyId = ''; sessionStorage.removeItem('emberline_demo_journey'); startDemo('EMBER-BUILDER'); }); $('#demoNextButton').addEventListener('click', advanceDemo);
document.querySelectorAll('[data-token]').forEach((button) => button.addEventListener('click', () => { $('#actorToken').value = button.dataset.token; }));
document.querySelectorAll('[data-demo-code]').forEach((button) => button.addEventListener('click', () => { $('#demoCode').value = button.dataset.demoCode; startDemo(button.dataset.demoCode); })); $('#startDemoButton').addEventListener('click', () => startDemo()); $('#demoCode').addEventListener('keydown', (event) => { if (event.key === 'Enter') startDemo(); });
$('#guideButton').addEventListener('click', () => openGuide()); $('#onboardingClose').addEventListener('click', () => closeGuide()); $('#onboardingSkip').addEventListener('click', () => closeGuide()); $('#onboardingBack').addEventListener('click', () => moveGuide(-1)); $('#onboardingNext').addEventListener('click', () => moveGuide(1));
$('#coachmarkEnd').addEventListener('click', endCoachTour); $('#coachmarkBack').addEventListener('click', () => moveCoach(-1)); $('#coachmarkNext').addEventListener('click', () => moveCoach(1)); window.addEventListener('resize', positionCoachmark);
document.addEventListener('keydown', (event) => { if ($('#coachmark').classList.contains('open')) { if (event.key === 'Escape') endCoachTour(); if (event.key === 'ArrowLeft') moveCoach(-1); if (event.key === 'ArrowRight') moveCoach(1); return; } if (!$('#onboarding').classList.contains('open')) return; if (event.key === 'Escape') closeGuide(); if (event.key === 'ArrowLeft') moveGuide(-1); if (event.key === 'ArrowRight') moveGuide(1); });

(async () => { try { const health = await request('/health'); const chain = health.attestcoin || {}; $('#chainStatus').textContent = chain.mode === 'unconfigured' ? 'Adapter · configure Attestcoin' : `${chain.network} · ${chain.mode}`; $('#persistenceStatus').textContent = health.persistence === 'postgresql' ? 'POSTGRESQL DATA' : 'LOCAL SQLITE DATA'; if (!health.demoCredentials) $('#demoCredentials').hidden = true; if (!health.demoExperienceEnabled) $('#publicDemo').hidden = true; await loadSession(); await loadProjects(state.actor?.demo ? state.actor.projectId : undefined); } catch (error) { showToast(error.message, true); } })();
